
title: "FishKar"
description: "A no-nonsense productivity tool for Fish shell"
color_scheme: dark
remote_theme: pmarsceill/just-the-docs
color_scheme: dark
# Navigation Sidebar
nav_order: 1
nav:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about"
  - title: "Installation"
    url: "/installation"
  - title: "Usage"
    url: "/usage"

# Search Feature
search_enabled: true
